### ISSUE TITLE
[internal library] Implement Symbol.iterator in Enumerable and IndexedArray

### ISSUE THREAD

**Issue by EternalQuasar0206** [MelonRuntime/Melon#102]
Implementation will help to build scalable solutions to manage data like database results and related
Type iterator (Reference: https://www.typescriptlang.org/docs/handbook/iterators-and-generators.html)

**Comment by EternalQuasar0206** [comment]
- Enumerable: [[code](https://github.com/MelonRuntime/MelonRuntime/blob/main/projects/melon-runtime/MelonJs.JavaScript/Bindings/Constructors/Enumerable.js)|[type](https://github.com/MelonRuntime/MelonRuntime/blob/main/projects/melon-types/lib/types/Constructors/Enumerable.d.ts)]
- IndexedArray: [[code](https://github.com/MelonRuntime/MelonRuntime/blob/main/projects/melon-runtime/MelonJs.JavaScript/Bindings/Constructors/IndexedArray.js)|[type](https://github.com/MelonRuntime/MelonRuntime/blob/main/projects/melon-types/lib/types/Constructors/IndexedArray.d.ts)]

**Comment by ktfth** [comment]
I'm gonna iterate to help on this implementation

**Comment by EternalQuasar0206** [comment]
@ktfth assigned

**Comment by EternalQuasar0206** [comment]
Solved in #116
