### ISSUE TITLE
[tests] setup unit tests in the melon-runtime project (both C# [xunit] and JavaScript [jest internal api])

### ISSUE THREAD

**Issue by victoriaquasar** [MelonRuntime/Melon#103]

**Comment by ktfth** [comment]
Can you explain what parts need to be covered at first step?

**Comment by victoriaquasar** [comment]
@ktfth Full internal coverage with unit tests is the first objective

**Comment by victoriaquasar** [comment]
Update: xunit tests started to be written in [development](https://github.com/MelonRuntime/Melon/tree/development) branch

**Comment by victoriaquasar** [comment]
Solved in #130
