### ISSUE TITLE
[melon-runtime] Internal method to read and convert functions into strings

### ISSUE THREAD

**Issue by victoriaquasar** [MelonRuntime/Melon#16]
Currently, there are no methods to convert `functions` into strings due to limitations at Jint engine. I currently can not figure out how to do that, but I have ideas to check the `function` type when passed to C# by the interpreter.

Currently `.toString()` returns `function() { [native code] }`

**Comment by EternalQuasar0206** [comment]
Update: I could use [Esprima](https://esprima.org/) to handle the code and get the function declarations, so, convert it to string. Thinking about that.

**Comment by EternalQuasar0206** [comment]
Implemented **workaround** to imported functions and expression functions in [PR24](https://github.com/MelonRuntime/MelonJS/pull/24)

**Comment by ktfth** [comment]
Just to understand, you need the behavior of  `someFunction.constructor.toString()`?

**Comment by victoriaquasar** [comment]
@ktfth yes

**Comment by minsk-dev** [comment]
I............... may do this...................
