### ISSUE TITLE
[melon-runtime] Create CORS options in http.app and HttpApplication

### ISSUE THREAD

**Issue by victoriaquasar** [MelonRuntime/Melon#90]
Implement options binding with `UseCors` in `MelonHttpApplication` and `WebApplicationManager`, like the example:

```cs
 app.UseCors(builder => builder
 .AllowAnyOrigin()
 .AllowAnyMethod()
 .AllowAnyHeader()
 .AllowCredentials());
```

**Comment by EternalQuasar0206** [comment]
Maybe a route method generator (curried function generator) can be used to handle method, header and credentials management
