### ISSUE TITLE
[internal library] implement `http.static` to serve static bundled files

### ISSUE THREAD

**Issue by EternalQuasar0206** [MelonRuntime/Melon#94]
- implement `http.static` to serve static bundled files in `melon-runtime`
- implement `http.static` types in `melon-types`

**Comment by vilanz** [comment]
willing to take this one

**Comment by EternalQuasar0206** [comment]
@vilanz assigned

**Comment by EternalQuasar0206** [comment]
update(implementations [runtime|1.7.0-next.1] [types|1.9.0-next.0]): #98

**Comment by EternalQuasar0206** [comment]
Solved in #107
